substitutions:
  name: "zigbee-network-radio"
  version: dev
packages:
  tubeszb.efr32_mgm24: github://tube0013/tube_gateways/models/current/tubeszb-efr32-MGM24/firmware/ESPHome/tubeszb-mgm24.yaml
  willowbird-ota: !include
    file: common/cicd.yaml
api:
  encryption:
    key: tJUHe0ttnXgoxZVYHc2xSAsFxwXucIvI+5MMqKXcN1Y=
