substitutions:
  name: "zigbee-network-radio"
packages:
  tubeszb-mgm24: !include
    file: vendor/tubeszb-mgm24.yaml
  willowbird-core: !include
    file: common/core.yaml
  willowbird-cicd: !include
    file: common/cicd.yaml
