substitutions:
  name: "zwave-network-radio"
packages:
  tubezb.zw: github://tube0013/tube_gateways/models/current/tubeszb-zw-kit/tubeszb-zw.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: ZfAzCacibEsmQYjFLvQZv2W1HyuHClPs9hfeJCGrPHc=
