substitutions:
  name: "zwave-network-radio"
  version: dev
packages:
  tubezb.zw: github://tube0013/tube_gateways/models/current/tubeszb-zw-kit/tubeszb-zw.yaml
  willowbird-ota: !include
    file: common/cicd.yaml
api:
  encryption:
    key: ZfAzCacibEsmQYjFLvQZv2W1HyuHClPs9hfeJCGrPHc=
