substitutions:
  name: "zwave-network-radio"
packages:
  tubeszb-zw: !include
    file: vendor/tubeszb-zw.yaml
  willowbird-core: !include
    file: common/core.yaml
  willowbird-cicd: !include
    file: common/cicd.yaml
