#!/usr/bin/env bash
#
# Manual push helper for willowbird-devices (issue #4).
#
# Wraps ESPHome for local/dev flashing and pulls secrets from Bitwarden via
# rbw (issue #6). Builds are "dev" builds: version stays "dev" and auto_update
# defaults to false, so a manually-pushed device never self-updates from the
# GitHub `latest` release (issue #5). Mainline builds only ever come from CI.
#
# Usage:
#   scripts/push.sh secrets                 Fetch secrets from Bitwarden -> devices/secrets.yaml
#   scripts/push.sh flash <device> [target] Compile + upload (USB or OTA). Auto-detects if no target.
#   scripts/push.sh ota <device> <target>   Upload over the network to <target> (host/IP)
#   scripts/push.sh bootstrap <device> [port]  First-time USB flash of a new device
#   scripts/push.sh logs <device> [target]  Stream logs from a device
#
# <device> is a config basename (e.g. bluetooth-proxy) or a path to a .yaml.
# <target> is a serial port (/dev/tty.*) or a network host/IP; omit to let
# ESPHome prompt.
#
# Env:
#   WILLOWBIRD_BW_ITEM   Bitwarden item name holding the secret fields
#                        (default: willowbird-devices)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEVICES_DIR="$REPO_ROOT/devices"
SECRETS_FILE="$DEVICES_DIR/secrets.yaml"
BW_ITEM="${WILLOWBIRD_BW_ITEM:-willowbird-devices}"

# Secret keys to pull. The first two are required; the rest are written only if
# present in the vault item (unused secrets are harmless to ESPHome).
REQUIRED_FIELDS=(wifi_ssid wifi_password)
OPTIONAL_FIELDS=(api_encryption_key ota_password)

die() { echo "error: $*" >&2; exit 1; }

require() { command -v "$1" >/dev/null 2>&1 || die "'$1' not found on PATH"; }

usage() { sed -n '2,/^set -euo/p' "$0" | sed 's/^# \{0,1\}//; /^set -euo/d'; }

# Resolve a device argument to a config path.
resolve_config() {
  local arg="$1"
  if [ -f "$arg" ]; then echo "$arg"; return; fi
  local c
  for c in "$DEVICES_DIR/$arg.yaml" "$REPO_ROOT/prototypes/$arg.yaml"; do
    [ -f "$c" ] && { echo "$c"; return; }
  done
  die "no config found for '$arg' (looked in devices/ and prototypes/)"
}

ensure_secrets() {
  [ -f "$SECRETS_FILE" ] || die "no $SECRETS_FILE — run: $0 secrets"
}

cmd_secrets() {
  require rbw
  # Unlock the vault (no-op if already unlocked).
  rbw unlock

  local tmp; tmp="$(mktemp)"
  {
    echo "# Generated by scripts/push.sh from Bitwarden item '$BW_ITEM'."
    echo "# Do NOT commit — this file is gitignored. Regenerate: scripts/push.sh secrets"
  } > "$tmp"

  local f val
  for f in "${REQUIRED_FIELDS[@]}"; do
    val="$(rbw get --field "$f" "$BW_ITEM" 2>/dev/null || true)"
    [ -n "$val" ] || die "required field '$f' not found in Bitwarden item '$BW_ITEM'"
    printf '%s: "%s"\n' "$f" "$val" >> "$tmp"
  done
  for f in "${OPTIONAL_FIELDS[@]}"; do
    val="$(rbw get --field "$f" "$BW_ITEM" 2>/dev/null || true)"
    [ -n "$val" ] && printf '%s: "%s"\n' "$f" "$val" >> "$tmp"
  done

  mv "$tmp" "$SECRETS_FILE"
  chmod 600 "$SECRETS_FILE"
  echo "Wrote $SECRETS_FILE"
}

cmd_flash() {
  local device="${1:-}"; [ -n "$device" ] || die "usage: $0 flash <device> [target]"
  local target="${2:-}"
  require esphome
  ensure_secrets
  local cfg; cfg="$(resolve_config "$device")"
  # Dev build: version=dev, auto_update=false are the config defaults.
  if [ -n "$target" ]; then
    esphome run "$cfg" --device "$target"
  else
    esphome run "$cfg"
  fi
}

cmd_ota() {
  local device="${1:-}" target="${2:-}"
  [ -n "$device" ] && [ -n "$target" ] || die "usage: $0 ota <device> <target>"
  require esphome
  ensure_secrets
  local cfg; cfg="$(resolve_config "$device")"
  esphome run "$cfg" --device "$target"
}

cmd_bootstrap() {
  local device="${1:-}"; [ -n "$device" ] || die "usage: $0 bootstrap <device> [port]"
  local port="${2:-}"
  require esphome
  # A fresh device has no secrets on it and no network; refresh secrets, then
  # flash over the serial port (never OTA for a first flash).
  cmd_secrets
  local cfg; cfg="$(resolve_config "$device")"
  if [ -n "$port" ]; then
    esphome run "$cfg" --device "$port"
  else
    echo "No port given — ESPHome will prompt. Pick the USB serial device."
    esphome run "$cfg"
  fi
}

cmd_logs() {
  local device="${1:-}"; [ -n "$device" ] || die "usage: $0 logs <device> [target]"
  local target="${2:-}"
  require esphome
  local cfg; cfg="$(resolve_config "$device")"
  if [ -n "$target" ]; then
    esphome logs "$cfg" --device "$target"
  else
    esphome logs "$cfg"
  fi
}

main() {
  local sub="${1:-}"; shift || true
  case "$sub" in
    secrets)   cmd_secrets "$@" ;;
    flash)     cmd_flash "$@" ;;
    ota)       cmd_ota "$@" ;;
    bootstrap) cmd_bootstrap "$@" ;;
    logs)      cmd_logs "$@" ;;
    ""|-h|--help|help) usage ;;
    *) die "unknown command '$sub' (try: $0 --help)" ;;
  esac
}

main "$@"
